## Multivariate Logistic regression on Iris dataset using cross entropy loss function

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_iris
ds = load_iris()

In [3]:
type(ds)

sklearn.datasets.base.Bunch

In [4]:
ds

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [5]:
ds.feature_names    #or ds['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
ds.target_names    #or ds['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
ds.data     #or ds['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
ds.target    #or ds['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
ds.data.shape

(150, 4)

In [10]:
ds.target.shape

(150,)

In [11]:
pd.Series(ds.target).value_counts()

2    50
1    50
0    50
dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
for i in range(ds['data'].shape[1]):
    ds['data'][:, i] = StandardScaler().fit_transform(ds['data'][:, i].reshape(-1, 1)).flatten()
    
    #reshape(-1, 1) means after reshape, row is of unknown dimension which will be figured out by numpy but column is of dimension 1. 

In [13]:
ds.data

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

## Flowchart :

<img src="logistic.png">

## Theory:
Source: coursera.org

<img src="log2.JPG">
<img src="log2.5.png">
<img src="log3.JPG">

In [14]:
learning_rate = 0.001
n_epochs = 50

# Weight initialization
w = np.zeros(5)     # four for features and one for bias

for e in range(n_epochs):
    acc_epoch = 0        #accuracy at each epoch
    loss_epoch = 0       #loss at each epoch
    
    for i in range(ds['data'].shape[0]):         #ds['data'].shape[0] is total number of rows in dataset ie. 150
        x = ds['data'][i, :]                     #ds['data'][i, :] is ith row and all columns
        y = int(ds['target'][i] != 0)            #ds['target'][i] is target value at ith row

        # Regression / Hypothesis equation
        z = w[0] + np.sum(x * w[1:])
        
        # Sigmoid Equation
        p = 1/(1+np.exp(-z))
        
        # make a decision
        y_pred = int(p >= 0.5)
        
        # update accuracy
        if y_pred == y:
            acc_epoch += 1
            
        # calculate and update cross-entropy loss value
        loss_epoch += -(y * np.log(p) + (1-y) * np.log(1-p))  
        
        # update weights of the model
        w[0] -= learning_rate * (p-y) * 1
        
        for j in range(x.shape[0]):
            w[j + 1] -= learning_rate * (p-y) * x[j]
        
    # average accuracy and loss
    acc_epoch /= ds['data'].shape[0]
    loss_epoch /= ds['data'].shape[0]
    
    print("At epoch " + str(e) + ':' + ' Accuracy : ' + str(acc_epoch) + " "*10 + 'Loss : ' + str(loss_epoch) + '\n')

At epoch 0: Accuracy : 0.96          Loss : 0.6528111380885625

At epoch 1: Accuracy : 0.9933333333333333          Loss : 0.581164305957222

At epoch 2: Accuracy : 0.9933333333333333          Loss : 0.5226005581235463

At epoch 3: Accuracy : 0.9933333333333333          Loss : 0.4743056455314175

At epoch 4: Accuracy : 0.9933333333333333          Loss : 0.4340636663748048

At epoch 5: Accuracy : 1.0          Loss : 0.40016604202782335

At epoch 6: Accuracy : 1.0          Loss : 0.37130600766796784

At epoch 7: Accuracy : 1.0          Loss : 0.34648422564209497

At epoch 8: Accuracy : 1.0          Loss : 0.3249328596030666

At epoch 9: Accuracy : 1.0          Loss : 0.3060575285873605

At epoch 10: Accuracy : 1.0          Loss : 0.28939400027234946

At epoch 11: Accuracy : 1.0          Loss : 0.27457620575224617

At epoch 12: Accuracy : 1.0          Loss : 0.2613126615741007

At epoch 13: Accuracy : 1.0          Loss : 0.24936903917553097

At epoch 14: Accuracy : 1.0          Loss : 0.23